services:
  postgres:
    image: postgres:15.5-alpine
    container_name: DemoApp-postgres
    environment:
      POSTGRES_DB: DemoAppDb
      POSTGRES_USER: SDL_Admin
      POSTGRES_PASSWORD: SDL_Admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      DemoApp-network:
        aliases:
          - DemoApp
          - postgres-db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: DemoApp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demoApp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - DemoApp-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  DemoApp-network:
    driver: bridge